OrdererOrgs:
  - Name: Orderer
    Domain: solo.network
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.solo.network
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.solo.network
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1