OrdererOrgs:
  - Name: Orderer
    Domain: kafka.network
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
PeerOrgs:
  - Name: Org1
    Domain: org1.kafka.network
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.kafka.network
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1