---
name: "Org2"

description: "My consortium - client definition for Org2"

version: '1.0'

#
# Channel definition
#
channels:
  mychannel:
    orderers:
      - orderer.fabric.network
      
    peers:
      peer0.org1.fabric.network:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.fabric.network:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - 'mycc:v1.0'

#
# List of participating organizations in this consortium
#
organizations:
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.fabric.network
    certificateAuthorities:
      - ca.org2.fabric.network
    adminPrivateKey: 
      path: orgs/assets/crypto-config/peerOrganizations/org2.fabric.network/users/Admin@org2.fabric.network/msp/keystore/secret.key
    signedCert:
      path: orgs/assets/crypto-config/peerOrganizations/org2.fabric.network/users/Admin@org2.fabric.network/msp/signcerts/Admin@org2.fabric.network-cert.pem

  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.fabric.network


#
# List of orderers
#
orderers:
  orderer.fabric.network:
    url: grpcs://orderer.fabric.network:7050

    grpcOptions:
      ssl-target-name-override: orderer.fabric.network
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: orgs/assets/crypto-config/ordererOrganizations/fabric.network/orderers/orderer.fabric.network/tls/ca.crt
#
# List of peers
#
peers:
  peer0.org1.fabric.network:
    # this URL is used to send endorsement and query requests
    url: grpcs://peer0.org1.fabric.network:7051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://peer0.org1.fabric.network:7053

    grpcOptions:
      ssl-target-name-override: peer0.org1.fabric.network
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: orgs/assets/crypto-config/peerOrganizations/org1.fabric.network/peers/peer0.org1.fabric.network/tls/ca.crt

  peer0.org2.fabric.network:
    url: grpcs://peer0.org2.fabric.network:7051
    eventUrl: grpcs://peer0.org2.fabric.network:7053
    grpcOptions:
      ssl-target-name-override: peer0.org2.fabric.network
    tlsCACerts:
      path: orgs/assets/crypto-config/peerOrganizations/org2.fabric.network/peers/peer0.org2.fabric.network/tls/ca.crt

#
# Certificate authorities
#
certificateAuthorities:
  ca.org2.fabric.network:
    url: https://ca.org2.fabric.network:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: orgs/assets/crypto-config/peerOrganizations/org2.fabric.network/ca/ca.org2.fabric.network-cert.pem

    registrar:
       enrollId: admin
       enrollSecret: adminpw
    caName: ca.org2.fabric.network

#
# The client section is SDK-specific.
#
client:
  organization: Org2

  credentialStore:
    path: "./org2-wallet/key-value"

    cryptoStore:
      path: "./org2-wallet/crypto"